### PR TITLE
added a project

### PR DESCRIPTION
**Pull request by Bikaskumar572**
added a weather website 
heroku link : https://bikas-weather-application.herokuapp.com/

### CODE REVIEW

**Comment by Bikaskumar572** [comment]
@piyush-kash , have a look on my pr

**Comment by piyush-kash** [comment]
just upload a DS problem

**Comment by Bikaskumar572** [comment]
@piyush-kash , done delete project and added cpp code

**Comment by Bikaskumar572** [comment]
@piyush-kash

**Pull request closed without merging**
