### PR TITLE
BinaryInsertionSort.java

### PR DESCRIPTION
**Pull request by diabl0-NEMESIS**
Implementation of Binary Insertion Sort.

### CODE REVIEW

**Comment by diabl0-NEMESIS** [comment]
Hi @piyush-kash, can you please merge this PR?
Thanks & Regards,
Abhishek

**Comment by piyush-kash** [comment]
read rules again

**Comment by diabl0-NEMESIS** [comment]
Hi Piyush,
i have gone through the rules
may i know what exactly do you feel is wrong in my PR

**Comment by piyush-kash** [comment]
did u star this repo?

**Comment by diabl0-NEMESIS** [comment]
ok staring

**Comment by diabl0-NEMESIS** [comment]
anything else?

**Pull request merged**
